# NAME: Ryan Miyahara
# EMAIL: rmiyahara144@gmail.com
# ID: 804585999

default:
	gcc -Wall -Wextra -g lab1.c -o lab1

clean:
	rm -f lab1 *.o *.txt *tar.gz

dist:
	make;
	tar -czf lab1-804585999.tar.gz ./lab1.c ./Makefile ./README