# NAME: Ryan Miyahara
# EMAIL: rmiyahara144@gmail.com
# ID: 804585999
# SLIPDAYS: 2

default:
	gcc -Wall -Wextra -g lab1a.c -o lab1a

clean:
	rm -f lab1a *.o *tar.gz

dist:
	make;
	tar -czf lab1a-804585999.tar.gz ./lab1a.c ./Makefile ./README
