#NAME: Ryan Miyahara
#EMAIL: rmiyahara144@gmail.com
#ID: 804585999

ifndef VERBOSE
.SILENT:
endif

default:
	gcc -Wall -Wextra -lmraa -g lab4b.c -o lab4b
check:

clean:
	rm -f ./lab4b-804585999.tar.gz ./lab4b

dist: default
	tar -zcf lab24b-804585999.tar.gz ./Makefile ./README