# NAME: Ryan Miyahara
# EMAIL: rmiyahara144@gmail.com
# ID: 804585999

default:
	tar -czf lab4a-804585999.tar.gz ./my_beaglebone.jpg ./connected.png ./copy.png ./build_run.png ./git.png ./Makefile ./README

clean:
	rm -f *.o *tar.gz

trivial:
	gcc trivial.c -o trivial
	