#Name: Ryan Miyahara
#Email: rmiyahara144@gmail.com
#ID: 804585999

default:
	gcc -Wall -Wextra -g lab0.c -o lab0

check:
	#TODO: check command

clean:
	rm -f lab0 *.o *.txt *tar.gz

dist:
	tar -czf lab0-804585999.tar.gz ./lab0.c ./Makefile ./README ./backtrace.png ./breakpoint.png
