default:
	gcc -Wall -Wextra -g src.c -o lab0

check:
	#TODO: check command

clean:
	rm -f lab0 *.o *.txt *tar.gz

dist:
	tar -czf lab0-804585999.tar.gz ./src.c ./Makefile ./README.md ./backtrace.png ./breakpoint.png
